### ISSUE TITLE
Buffer is not defined and process is not defined

### ISSUE THREAD

**Issue by rudyaditya** [remorses/esbuild-plugins#31]
I have problem in my project although I already use NodeModulesPolyfillPlugin().
I always get Buffer is not defined error. 
When I search in the plugins package I find that the code uses Buffer from node library (node_modules/@types/node)

`
> Buffer is not defined

We dynamically generated a new test to display this failure.
View stack trace
 Print to console
    at ApiClient.encryptBasicToken (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:82752:27)
    at new ApiClient (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:82734:112)
    at client (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:82720:25)
    at node_modules/@xendit/xenqa/xray/api.js (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:83865:34)
    at __require2 (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:19:52)
    at node_modules/@xendit/xenqa/xray/index.js (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:84113:19)
    at __require2 (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:19:52)
    at node_modules/@xendit/xenqa/ui/support/index.js (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:84214:7)
    at __require2 (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:19:52)
    at eval (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:93845:32)
From previous event:
    at evalScripts (http://localhost:53944/__cypress/runner/cypress_runner.js:158706:58)
    at <unknown> (http://localhost:53944/__cypress/runner/cypress_runner.js:158715:152)
From previous event:
    at runScriptsFromUrls (http://localhost:53944/__cypress/runner/cypress_runner.js:158715:136)
    at Object.runScripts (http://localhost:53944/__cypress/runner/cypress_runner.js:158729:12)
    at $Cypress.onSpecWindow (http://localhost:53944/__cypress/runner/cypress_runner.js:147444:75)

ChromeChrome 109

1000x660
(56%)

`
I also get process is not defined, when I import package from 'fs-extra' 
https://github.com/jprichardson/node-fs-extra

`
  process is not defined

View stack trace
 Print to console
    at node_modules/graceful-fs/polyfills.js (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:22118:21)
    at __require2 (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:17:52)
    at node_modules/graceful-fs/graceful-fs.js (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:27150:23)
    at __require2 (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:17:52)
    at node_modules/fs-extra/lib/fs/index.js (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:27521:17)
    at __require2 (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:17:52)
    at node_modules/fs-extra/lib/index.js (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:29496:12)
    at __require2 (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:17:52)
    at eval (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:30931:12)
    at eval (http://localhost:53944/__cypress/tests?p=cypress/support/e2e.js:30938:3)
From previous event:
    at evalScripts (http://localhost:53944/__cypress/runner/cypress_runner.js:158706:58)
    at <unknown> (http://localhost:53944/__cypress/runner/cypress_runner.js:158715:152)
From previous event:
    at runScriptsFromUrls (http://localhost:53944/__cypress/runner/cypress_runner.js:158715:136)
    at Object.runScripts (http://localhost:53944/__cypress/runner/cypress_runner.js:158729:12)
    at $Cypress.onSpecWindow (http://localhost:53944/__cypress/runner/cypress_runner.js:147444:75)`

**Comment by rudyaditya** [comment]
I solve this issue by using Cypress.Buffer in my project 
https://docs.cypress.io/api/utilities/buffer
